title: "snamjoshi.github.io"
author: Sanjeev Namjoshi
email: sanjeev.namjoshi@gmail.com
description: Sanjeev Namjoshi's personal webpage.

github_username: snamjoshi
linkedin_username: snamjoshi

header_pages:
  - faif.md
  - research.md
  - papers.md

theme: minima