title: "Home"
description: Sanjeev Namjoshi's personal webpage.

social-network-links:
  email: sanjeev.namjoshi@gmail.com
  github_username: snamjoshi
  linkedin: snamjoshi
  discord: users/sanjeev_namjoshi

header_pages:
  - faif.md
  - research.md

theme: minima