title: "snamjoshi.github.io"
author: Sanjeev Namjoshi
email: sanjeev.namjoshi@gmail.com
description: Sanjeev Namjoshi's personal webpage.

github_username: snamjoshi
linkedin_username: snamjoshi
discord_username: users/sanjeev_namjoshi

minima:
  header_pages:
    - faif.md
    - research.md

theme: minima